name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        python-version: [2.7.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7.x
      uses:actions/setup-python@v2
      with:
        python-version: 2.7.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
            pytest test_calculator.py
